blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/horix-dev/posmate-electron-client/discussions
    about: Please use Discussions for Q&A and general support.
